// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = {
    git_http_backend: require("./git-http-backend"),
    raw: require("./raw"),
    browse: require("./browse"),
    object: require("./object"),
    commit: require("./commit"),
    refs: require("./refs")
  };

}).call(this);


