// Generated by CoffeeScript 1.12.7
(function() {
  var mock;

  mock = require("mockery");

  mock.registerMock("path-to-regexp", require("path-to-regexp"));

  mock.registerMock("events", require("events-as-promised"));

  mock.enable({
    warnOnUnregistered: false,
    useCleanCache: true
  });

  module.exports = require("express");

  mock.disable();

}).call(this);


